### ISSUE TITLE
Atomic and Exodus not open source

### ISSUE THREAD

**Issue by lgvz** [nanowallets-guide/nanowallets-json#24]
The Atomic and Exodus wallets are listed as open source but neither one is. There are some open source libraries on their github but not the wallets themselves.

Also confirmed by these pages:
https://support.exodus.io/article/89-is-exodus-open-source
https://atomicwallet.io/terms-of-service

Relevant part from Atomic ToS: "You are not permitted to redistribute any of Atomic Services, modify any code or use any Atomic content, including images and text, as part of any other software or project of any kind" (section 4). That doesn't quite say source isn't available for reading, but basically people use the term "open source" for FOSS, don't they? And the source is nowhere to be found anyway (I even asked their support).

For the description of "open source" on you readme, "If core parts (core as in handling of funds) of the wallet are open source.", that's a custom definition not mentioned on the web site, and neither Atomic nor Exodus fulfill that definition anyway. You cannot even confirm the wallets are using any of the libraries on github, since the wallet source itself isn't available.

Please do the honest thing and list them as proprietary, because otherwise people have to waste time digging up the truth, like I did.

Proprietary until proven otherwise.

**Comment by Joohansson** [comment]
I'm ok with the change and make them non-open source

**Comment by nanowallets-guide** [comment]
Yes me too. I will address this later today. Thanks for the feedback @lgvz!
